name:  angular_flow_type
version: 0.0.1
description: >
  FlowType port for Angular.dart
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/dart-ng-flow-type

dependencies:
  angular: "0.9.8"
  
dev_dependencies: 
  unittest: any
  browser: ">=0.9.1 <0.9.2"