name:  angular_flow_type
version: 0.2.1
description: >
  FlowType port for Angular.dart
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/dart-ng-flow-type

dependencies:
  angular: ">=0.11.0 <0.12.0"

dev_dependencies:
  unittest: ">=0.10.1+2 <0.11.0"
  browser: ">=0.10.0+2 <0.11.0"

transformers:
- angular