name:  angular_flow_type
version: 0.1.0
description: >
  FlowType port for Angular.dart
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/dart-ng-flow-type

dependencies:
  angular: ">=0.10.0"
  di: '>=0.0.40'
  shadow_dom: any
  
dev_dependencies: 
  unittest: any
  browser: any
  
transformers:
- angular